baseURL = 'https://cruxcook.github.io/cruxtrove/'
relativeURLs = true
languageCode = 'en-us'
title = 'Crux Trove'
canonifyUrls = true

paginate = 5

[params]
    description = "Projects Showcase"
    dateFormat = "Jan 02, 2006"

[taxonomies]
    category = "categories"
    author = "authors"