baseURL = '/'
uglyURLs = 'True'
relativeURLs = 'True'
languageCode = 'en-us'
title = 'Crux Trove'

paginate = 2

[params]
    dateFormat = "Jan 02, 2006"

[taxonomies]
    category = "categories"
    author = "authors"